// Generated by scripts/health_types.py. Do not edit by hand.

extension HealthDataGroup {
    public static let ordered: [HealthDataGroup] = [
        .activity,
        .body,
        .heart,
        .vitals,
        .respiratory,
        .mobility,
        .nutrition,
        .sleep,
        .mind,
        .hearing,
        .environment,
        .cycle,
        .symptoms,
        .habits,
        .workouts,
        .records,
        .profile,
    ]

    public var label: String {
        switch self {
        case .activity: "Aktivität"
        case .body: "Körpermaße"
        case .heart: "Herz"
        case .vitals: "Vitalwerte"
        case .respiratory: "Atmung"
        case .mobility: "Mobilität"
        case .nutrition: "Ernährung"
        case .sleep: "Schlaf"
        case .mind: "Achtsamkeit & Psyche"
        case .hearing: "Hören"
        case .environment: "Umgebung"
        case .cycle: "Zyklus & Fortpflanzung"
        case .symptoms: "Symptome"
        case .habits: "Gewohnheiten"
        case .workouts: "Trainings"
        case .records: "Gesundheitsakten"
        case .profile: "Profil"
        }
    }

    public var symbol: String {
        switch self {
        case .activity: "flame"
        case .body: "figure"
        case .heart: "heart"
        case .vitals: "waveform.path.ecg"
        case .respiratory: "lungs"
        case .mobility: "figure.walk"
        case .nutrition: "fork.knife"
        case .sleep: "bed.double"
        case .mind: "brain.head.profile"
        case .hearing: "ear"
        case .environment: "sun.max"
        case .cycle: "drop"
        case .symptoms: "bandage"
        case .habits: "hands.sparkles"
        case .workouts: "figure.run"
        case .records: "cross.case"
        case .profile: "person.text.rectangle"
        }
    }
}

extension HealthDataCatalog {
    public static let all: [HealthDataType] = [
        HealthDataType(id: "HKQuantityTypeIdentifierStepCount", kind: .quantity, group: .activity, label: "Schritte", aggregation: .sum),
        HealthDataType(id: "HKQuantityTypeIdentifierDistanceWalkingRunning", kind: .quantity, group: .activity, label: "Strecke Gehen und Laufen", aggregation: .sum),
        HealthDataType(id: "HKQuantityTypeIdentifierDistanceCycling", kind: .quantity, group: .activity, label: "Strecke Radfahren", aggregation: .sum),
        HealthDataType(id: "HKQuantityTypeIdentifierDistanceSwimming", kind: .quantity, group: .activity, label: "Strecke Schwimmen", aggregation: .sum),
        HealthDataType(id: "HKQuantityTypeIdentifierDistanceWheelchair", kind: .quantity, group: .activity, label: "Strecke Rollstuhl", aggregation: .sum),
        HealthDataType(id: "HKQuantityTypeIdentifierDistanceDownhillSnowSports", kind: .quantity, group: .activity, label: "Strecke Wintersport", aggregation: .sum),
        HealthDataType(id: "HKQuantityTypeIdentifierDistanceCrossCountrySkiing", kind: .quantity, group: .activity, label: "Strecke Langlauf", aggregation: .sum),
        HealthDataType(id: "HKQuantityTypeIdentifierDistancePaddleSports", kind: .quantity, group: .activity, label: "Strecke Paddeln", aggregation: .sum),
        HealthDataType(id: "HKQuantityTypeIdentifierDistanceRowing", kind: .quantity, group: .activity, label: "Strecke Rudern", aggregation: .sum),
        HealthDataType(id: "HKQuantityTypeIdentifierDistanceSkatingSports", kind: .quantity, group: .activity, label: "Strecke Skaten", aggregation: .sum),
        HealthDataType(id: "HKQuantityTypeIdentifierPushCount", kind: .quantity, group: .activity, label: "Rollstuhl-Anschübe", aggregation: .sum),
        HealthDataType(id: "HKQuantityTypeIdentifierSwimmingStrokeCount", kind: .quantity, group: .activity, label: "Schwimmzüge", aggregation: .sum),
        HealthDataType(id: "HKQuantityTypeIdentifierFlightsClimbed", kind: .quantity, group: .activity, label: "Etagen gestiegen", aggregation: .sum),
        HealthDataType(id: "HKQuantityTypeIdentifierNikeFuel", kind: .quantity, group: .activity, label: "NikeFuel", aggregation: .sum),
        HealthDataType(id: "HKQuantityTypeIdentifierAppleExerciseTime", kind: .quantity, group: .activity, label: "Trainingsminuten", aggregation: .sum),
        HealthDataType(id: "HKQuantityTypeIdentifierAppleMoveTime", kind: .quantity, group: .activity, label: "Bewegungsminuten", aggregation: .sum),
        HealthDataType(id: "HKQuantityTypeIdentifierAppleStandTime", kind: .quantity, group: .activity, label: "Stehminuten", aggregation: .sum),
        HealthDataType(id: "HKQuantityTypeIdentifierActiveEnergyBurned", kind: .quantity, group: .activity, label: "Aktive Energie", aggregation: .sum),
        HealthDataType(id: "HKQuantityTypeIdentifierBasalEnergyBurned", kind: .quantity, group: .activity, label: "Ruheenergie", aggregation: .sum),
        HealthDataType(id: "HKQuantityTypeIdentifierPhysicalEffort", kind: .quantity, group: .activity, label: "Körperliche Anstrengung", aggregation: .avg),
        HealthDataType(id: "HKQuantityTypeIdentifierWorkoutEffortScore", kind: .quantity, group: .activity, label: "Trainingsintensität", aggregation: .avg),
        HealthDataType(id: "HKQuantityTypeIdentifierEstimatedWorkoutEffortScore", kind: .quantity, group: .activity, label: "Geschätzte Trainingsintensität", aggregation: .avg),
        HealthDataType(id: "HKQuantityTypeIdentifierCyclingCadence", kind: .quantity, group: .activity, label: "Trittfrequenz", aggregation: .avg),
        HealthDataType(id: "HKQuantityTypeIdentifierCyclingPower", kind: .quantity, group: .activity, label: "Radleistung", aggregation: .avg),
        HealthDataType(id: "HKQuantityTypeIdentifierCyclingFunctionalThresholdPower", kind: .quantity, group: .activity, label: "Funktionelle Schwellenleistung", aggregation: .avg),
        HealthDataType(id: "HKQuantityTypeIdentifierCyclingSpeed", kind: .quantity, group: .activity, label: "Geschwindigkeit Radfahren", aggregation: .avg),
        HealthDataType(id: "HKQuantityTypeIdentifierRunningPower", kind: .quantity, group: .activity, label: "Laufleistung", aggregation: .avg),
        HealthDataType(id: "HKQuantityTypeIdentifierRunningSpeed", kind: .quantity, group: .activity, label: "Laufgeschwindigkeit", aggregation: .avg),
        HealthDataType(id: "HKQuantityTypeIdentifierRunningStrideLength", kind: .quantity, group: .activity, label: "Schrittlänge beim Laufen", aggregation: .avg),
        HealthDataType(id: "HKQuantityTypeIdentifierRunningVerticalOscillation", kind: .quantity, group: .activity, label: "Vertikale Bewegung beim Laufen", aggregation: .avg),
        HealthDataType(id: "HKQuantityTypeIdentifierRunningGroundContactTime", kind: .quantity, group: .activity, label: "Bodenkontaktzeit", aggregation: .avg),
        HealthDataType(id: "HKQuantityTypeIdentifierCrossCountrySkiingSpeed", kind: .quantity, group: .activity, label: "Geschwindigkeit Langlauf", aggregation: .avg),
        HealthDataType(id: "HKQuantityTypeIdentifierPaddleSportsSpeed", kind: .quantity, group: .activity, label: "Geschwindigkeit Paddeln", aggregation: .avg),
        HealthDataType(id: "HKQuantityTypeIdentifierRowingSpeed", kind: .quantity, group: .activity, label: "Geschwindigkeit Rudern", aggregation: .avg),
        HealthDataType(id: "HKQuantityTypeIdentifierUnderwaterDepth", kind: .quantity, group: .activity, label: "Tauchtiefe", aggregation: .avg),
        HealthDataType(id: "HKQuantityTypeIdentifierWaterTemperature", kind: .quantity, group: .environment, label: "Wassertemperatur", aggregation: .avg),
        HealthDataType(id: "HKQuantityTypeIdentifierHeight", kind: .quantity, group: .body, label: "Größe", aggregation: .avg),
        HealthDataType(id: "HKQuantityTypeIdentifierBodyMass", kind: .quantity, group: .body, label: "Gewicht", aggregation: .avg),
        HealthDataType(id: "HKQuantityTypeIdentifierBodyMassIndex", kind: .quantity, group: .body, label: "Body-Mass-Index", aggregation: .avg),
        HealthDataType(id: "HKQuantityTypeIdentifierLeanBodyMass", kind: .quantity, group: .body, label: "Fettfreie Körpermasse", aggregation: .avg),
        HealthDataType(id: "HKQuantityTypeIdentifierBodyFatPercentage", kind: .quantity, group: .body, label: "Körperfettanteil", aggregation: .avg),
        HealthDataType(id: "HKQuantityTypeIdentifierWaistCircumference", kind: .quantity, group: .body, label: "Taillenumfang", aggregation: .avg),
        HealthDataType(id: "HKQuantityTypeIdentifierBodyTemperature", kind: .quantity, group: .body, label: "Körpertemperatur", aggregation: .avg),
        HealthDataType(id: "HKQuantityTypeIdentifierBasalBodyTemperature", kind: .quantity, group: .cycle, label: "Basaltemperatur", aggregation: .avg),
        HealthDataType(id: "HKQuantityTypeIdentifierAppleSleepingWristTemperature", kind: .quantity, group: .sleep, label: "Handgelenktemperatur im Schlaf", aggregation: .avg),
        HealthDataType(id: "HKQuantityTypeIdentifierHeartRate", kind: .quantity, group: .heart, label: "Herzfrequenz", aggregation: .avg),
        HealthDataType(id: "HKQuantityTypeIdentifierRestingHeartRate", kind: .quantity, group: .heart, label: "Ruhepuls", aggregation: .avg),
        HealthDataType(id: "HKQuantityTypeIdentifierWalkingHeartRateAverage", kind: .quantity, group: .heart, label: "Durchschnittspuls beim Gehen", aggregation: .avg),
        HealthDataType(id: "HKQuantityTypeIdentifierHeartRateVariabilitySDNN", kind: .quantity, group: .heart, label: "Herzfrequenzvariabilität", aggregation: .avg),
        HealthDataType(id: "HKQuantityTypeIdentifierHeartRateRecoveryOneMinute", kind: .quantity, group: .heart, label: "Herzfrequenzerholung", aggregation: .avg),
        HealthDataType(id: "HKQuantityTypeIdentifierAtrialFibrillationBurden", kind: .quantity, group: .heart, label: "Vorhofflimmern-Anteil", aggregation: .avg),
        HealthDataType(id: "HKQuantityTypeIdentifierVO2Max", kind: .quantity, group: .heart, label: "Cardiofitness (VO₂max)", aggregation: .avg),
        HealthDataType(id: "HKQuantityTypeIdentifierPeripheralPerfusionIndex", kind: .quantity, group: .heart, label: "Perfusionsindex", aggregation: .avg),
        HealthDataType(id: "HKQuantityTypeIdentifierBloodPressureSystolic", kind: .quantity, group: .vitals, label: "Blutdruck systolisch", aggregation: .avg),
        HealthDataType(id: "HKQuantityTypeIdentifierBloodPressureDiastolic", kind: .quantity, group: .vitals, label: "Blutdruck diastolisch", aggregation: .avg),
        HealthDataType(id: "HKQuantityTypeIdentifierOxygenSaturation", kind: .quantity, group: .vitals, label: "Sauerstoffsättigung", aggregation: .avg),
        HealthDataType(id: "HKQuantityTypeIdentifierBloodGlucose", kind: .quantity, group: .vitals, label: "Blutzucker", aggregation: .avg),
        HealthDataType(id: "HKQuantityTypeIdentifierElectrodermalActivity", kind: .quantity, group: .vitals, label: "Elektrodermale Aktivität", aggregation: .avg),
        HealthDataType(id: "HKQuantityTypeIdentifierInsulinDelivery", kind: .quantity, group: .vitals, label: "Insulin", aggregation: .sum),
        HealthDataType(id: "HKQuantityTypeIdentifierBloodAlcoholContent", kind: .quantity, group: .vitals, label: "Blutalkohol", aggregation: .avg),
        HealthDataType(id: "HKQuantityTypeIdentifierNumberOfAlcoholicBeverages", kind: .quantity, group: .vitals, label: "Alkoholische Getränke", aggregation: .sum),
        HealthDataType(id: "HKQuantityTypeIdentifierNumberOfTimesFallen", kind: .quantity, group: .vitals, label: "Stürze", aggregation: .sum),
        HealthDataType(id: "HKQuantityTypeIdentifierRespiratoryRate", kind: .quantity, group: .respiratory, label: "Atemfrequenz", aggregation: .avg),
        HealthDataType(id: "HKQuantityTypeIdentifierAppleSleepingBreathingDisturbances", kind: .quantity, group: .respiratory, label: "Atemstörungen im Schlaf", aggregation: .avg),
        HealthDataType(id: "HKQuantityTypeIdentifierInhalerUsage", kind: .quantity, group: .respiratory, label: "Inhalator-Nutzung", aggregation: .sum),
        HealthDataType(id: "HKQuantityTypeIdentifierForcedVitalCapacity", kind: .quantity, group: .respiratory, label: "Forcierte Vitalkapazität", aggregation: .avg),
        HealthDataType(id: "HKQuantityTypeIdentifierForcedExpiratoryVolume1", kind: .quantity, group: .respiratory, label: "Einsekundenkapazität (FEV1)", aggregation: .avg),
        HealthDataType(id: "HKQuantityTypeIdentifierPeakExpiratoryFlowRate", kind: .quantity, group: .respiratory, label: "Spitzenfluss", aggregation: .avg),
        HealthDataType(id: "HKQuantityTypeIdentifierWalkingSpeed", kind: .quantity, group: .mobility, label: "Gehgeschwindigkeit", aggregation: .avg),
        HealthDataType(id: "HKQuantityTypeIdentifierWalkingStepLength", kind: .quantity, group: .mobility, label: "Schrittlänge", aggregation: .avg),
        HealthDataType(id: "HKQuantityTypeIdentifierWalkingAsymmetryPercentage", kind: .quantity, group: .mobility, label: "Gang-Asymmetrie", aggregation: .avg),
        HealthDataType(id: "HKQuantityTypeIdentifierWalkingDoubleSupportPercentage", kind: .quantity, group: .mobility, label: "Doppelschrittphase", aggregation: .avg),
        HealthDataType(id: "HKQuantityTypeIdentifierStairAscentSpeed", kind: .quantity, group: .mobility, label: "Treppensteigen aufwärts", aggregation: .avg),
        HealthDataType(id: "HKQuantityTypeIdentifierStairDescentSpeed", kind: .quantity, group: .mobility, label: "Treppensteigen abwärts", aggregation: .avg),
        HealthDataType(id: "HKQuantityTypeIdentifierSixMinuteWalkTestDistance", kind: .quantity, group: .mobility, label: "6-Minuten-Gehtest", aggregation: .avg),
        HealthDataType(id: "HKQuantityTypeIdentifierAppleWalkingSteadiness", kind: .quantity, group: .mobility, label: "Gangstabilität", aggregation: .avg),
        HealthDataType(id: "HKQuantityTypeIdentifierEnvironmentalAudioExposure", kind: .quantity, group: .hearing, label: "Umgebungslautstärke", aggregation: .avg),
        HealthDataType(id: "HKQuantityTypeIdentifierHeadphoneAudioExposure", kind: .quantity, group: .hearing, label: "Kopfhörerlautstärke", aggregation: .avg),
        HealthDataType(id: "HKQuantityTypeIdentifierEnvironmentalSoundReduction", kind: .quantity, group: .hearing, label: "Lärmreduzierung", aggregation: .avg),
        HealthDataType(id: "HKQuantityTypeIdentifierUVExposure", kind: .quantity, group: .environment, label: "UV-Belastung", aggregation: .avg),
        HealthDataType(id: "HKQuantityTypeIdentifierTimeInDaylight", kind: .quantity, group: .environment, label: "Zeit bei Tageslicht", aggregation: .sum),
        HealthDataType(id: "HKQuantityTypeIdentifierDietaryEnergyConsumed", kind: .quantity, group: .nutrition, label: "Energie (Nahrung)", aggregation: .sum),
        HealthDataType(id: "HKQuantityTypeIdentifierDietaryProtein", kind: .quantity, group: .nutrition, label: "Eiweiß", aggregation: .sum),
        HealthDataType(id: "HKQuantityTypeIdentifierDietaryCarbohydrates", kind: .quantity, group: .nutrition, label: "Kohlenhydrate", aggregation: .sum),
        HealthDataType(id: "HKQuantityTypeIdentifierDietaryFatTotal", kind: .quantity, group: .nutrition, label: "Fett gesamt", aggregation: .sum),
        HealthDataType(id: "HKQuantityTypeIdentifierDietaryFatSaturated", kind: .quantity, group: .nutrition, label: "Gesättigte Fettsäuren", aggregation: .sum),
        HealthDataType(id: "HKQuantityTypeIdentifierDietaryFatMonounsaturated", kind: .quantity, group: .nutrition, label: "Einfach ungesättigte Fettsäuren", aggregation: .sum),
        HealthDataType(id: "HKQuantityTypeIdentifierDietaryFatPolyunsaturated", kind: .quantity, group: .nutrition, label: "Mehrfach ungesättigte Fettsäuren", aggregation: .sum),
        HealthDataType(id: "HKQuantityTypeIdentifierDietaryCholesterol", kind: .quantity, group: .nutrition, label: "Cholesterin", aggregation: .sum),
        HealthDataType(id: "HKQuantityTypeIdentifierDietaryFiber", kind: .quantity, group: .nutrition, label: "Ballaststoffe", aggregation: .sum),
        HealthDataType(id: "HKQuantityTypeIdentifierDietarySugar", kind: .quantity, group: .nutrition, label: "Zucker", aggregation: .sum),
        HealthDataType(id: "HKQuantityTypeIdentifierDietaryWater", kind: .quantity, group: .nutrition, label: "Wasser", aggregation: .sum),
        HealthDataType(id: "HKQuantityTypeIdentifierDietaryCaffeine", kind: .quantity, group: .nutrition, label: "Koffein", aggregation: .sum),
        HealthDataType(id: "HKQuantityTypeIdentifierDietarySodium", kind: .quantity, group: .nutrition, label: "Natrium", aggregation: .sum),
        HealthDataType(id: "HKQuantityTypeIdentifierDietaryPotassium", kind: .quantity, group: .nutrition, label: "Kalium", aggregation: .sum),
        HealthDataType(id: "HKQuantityTypeIdentifierDietaryCalcium", kind: .quantity, group: .nutrition, label: "Calcium", aggregation: .sum),
        HealthDataType(id: "HKQuantityTypeIdentifierDietaryIron", kind: .quantity, group: .nutrition, label: "Eisen", aggregation: .sum),
        HealthDataType(id: "HKQuantityTypeIdentifierDietaryMagnesium", kind: .quantity, group: .nutrition, label: "Magnesium", aggregation: .sum),
        HealthDataType(id: "HKQuantityTypeIdentifierDietaryPhosphorus", kind: .quantity, group: .nutrition, label: "Phosphor", aggregation: .sum),
        HealthDataType(id: "HKQuantityTypeIdentifierDietaryZinc", kind: .quantity, group: .nutrition, label: "Zink", aggregation: .sum),
        HealthDataType(id: "HKQuantityTypeIdentifierDietaryCopper", kind: .quantity, group: .nutrition, label: "Kupfer", aggregation: .sum),
        HealthDataType(id: "HKQuantityTypeIdentifierDietaryManganese", kind: .quantity, group: .nutrition, label: "Mangan", aggregation: .sum),
        HealthDataType(id: "HKQuantityTypeIdentifierDietarySelenium", kind: .quantity, group: .nutrition, label: "Selen", aggregation: .sum),
        HealthDataType(id: "HKQuantityTypeIdentifierDietaryChromium", kind: .quantity, group: .nutrition, label: "Chrom", aggregation: .sum),
        HealthDataType(id: "HKQuantityTypeIdentifierDietaryMolybdenum", kind: .quantity, group: .nutrition, label: "Molybdän", aggregation: .sum),
        HealthDataType(id: "HKQuantityTypeIdentifierDietaryChloride", kind: .quantity, group: .nutrition, label: "Chlorid", aggregation: .sum),
        HealthDataType(id: "HKQuantityTypeIdentifierDietaryIodine", kind: .quantity, group: .nutrition, label: "Jod", aggregation: .sum),
        HealthDataType(id: "HKQuantityTypeIdentifierDietaryVitaminA", kind: .quantity, group: .nutrition, label: "Vitamin A", aggregation: .sum),
        HealthDataType(id: "HKQuantityTypeIdentifierDietaryVitaminB6", kind: .quantity, group: .nutrition, label: "Vitamin B6", aggregation: .sum),
        HealthDataType(id: "HKQuantityTypeIdentifierDietaryVitaminB12", kind: .quantity, group: .nutrition, label: "Vitamin B12", aggregation: .sum),
        HealthDataType(id: "HKQuantityTypeIdentifierDietaryVitaminC", kind: .quantity, group: .nutrition, label: "Vitamin C", aggregation: .sum),
        HealthDataType(id: "HKQuantityTypeIdentifierDietaryVitaminD", kind: .quantity, group: .nutrition, label: "Vitamin D", aggregation: .sum),
        HealthDataType(id: "HKQuantityTypeIdentifierDietaryVitaminE", kind: .quantity, group: .nutrition, label: "Vitamin E", aggregation: .sum),
        HealthDataType(id: "HKQuantityTypeIdentifierDietaryVitaminK", kind: .quantity, group: .nutrition, label: "Vitamin K", aggregation: .sum),
        HealthDataType(id: "HKQuantityTypeIdentifierDietaryThiamin", kind: .quantity, group: .nutrition, label: "Thiamin (B1)", aggregation: .sum),
        HealthDataType(id: "HKQuantityTypeIdentifierDietaryRiboflavin", kind: .quantity, group: .nutrition, label: "Riboflavin (B2)", aggregation: .sum),
        HealthDataType(id: "HKQuantityTypeIdentifierDietaryNiacin", kind: .quantity, group: .nutrition, label: "Niacin (B3)", aggregation: .sum),
        HealthDataType(id: "HKQuantityTypeIdentifierDietaryPantothenicAcid", kind: .quantity, group: .nutrition, label: "Pantothensäure (B5)", aggregation: .sum),
        HealthDataType(id: "HKQuantityTypeIdentifierDietaryBiotin", kind: .quantity, group: .nutrition, label: "Biotin", aggregation: .sum),
        HealthDataType(id: "HKQuantityTypeIdentifierDietaryFolate", kind: .quantity, group: .nutrition, label: "Folat", aggregation: .sum),
        HealthDataType(id: "HKCategoryTypeIdentifierSleepAnalysis", kind: .category, group: .sleep, label: "Schlafanalyse", aggregation: .count),
        HealthDataType(id: "HKCategoryTypeIdentifierSleepApneaEvent", kind: .category, group: .sleep, label: "Atemaussetzer im Schlaf", aggregation: .count),
        HealthDataType(id: "HKCategoryTypeIdentifierMindfulSession", kind: .category, group: .mind, label: "Achtsamkeitsminuten", aggregation: .count),
        HealthDataType(id: "HKCategoryTypeIdentifierAppleStandHour", kind: .category, group: .activity, label: "Stehstunden", aggregation: .count),
        HealthDataType(id: "HKCategoryTypeIdentifierHighHeartRateEvent", kind: .category, group: .heart, label: "Hohe Herzfrequenz", aggregation: .count),
        HealthDataType(id: "HKCategoryTypeIdentifierLowHeartRateEvent", kind: .category, group: .heart, label: "Niedrige Herzfrequenz", aggregation: .count),
        HealthDataType(id: "HKCategoryTypeIdentifierIrregularHeartRhythmEvent", kind: .category, group: .heart, label: "Unregelmäßiger Herzrhythmus", aggregation: .count),
        HealthDataType(id: "HKCategoryTypeIdentifierLowCardioFitnessEvent", kind: .category, group: .heart, label: "Niedrige Cardiofitness", aggregation: .count),
        HealthDataType(id: "HKCategoryTypeIdentifierEnvironmentalAudioExposureEvent", kind: .category, group: .hearing, label: "Laute Umgebung", aggregation: .count),
        HealthDataType(id: "HKCategoryTypeIdentifierHeadphoneAudioExposureEvent", kind: .category, group: .hearing, label: "Laute Kopfhörer", aggregation: .count),
        HealthDataType(id: "HKCategoryTypeIdentifierAppleWalkingSteadinessEvent", kind: .category, group: .mobility, label: "Gangstabilität-Hinweis", aggregation: .count),
        HealthDataType(id: "HKCategoryTypeIdentifierToothbrushingEvent", kind: .category, group: .habits, label: "Zähneputzen", aggregation: .count),
        HealthDataType(id: "HKCategoryTypeIdentifierHandwashingEvent", kind: .category, group: .habits, label: "Händewaschen", aggregation: .count),
        HealthDataType(id: "HKCategoryTypeIdentifierMenstrualFlow", kind: .category, group: .cycle, label: "Periode", aggregation: .count),
        HealthDataType(id: "HKCategoryTypeIdentifierIntermenstrualBleeding", kind: .category, group: .cycle, label: "Zwischenblutung", aggregation: .count),
        HealthDataType(id: "HKCategoryTypeIdentifierInfrequentMenstrualCycles", kind: .category, group: .cycle, label: "Seltene Zyklen", aggregation: .count),
        HealthDataType(id: "HKCategoryTypeIdentifierIrregularMenstrualCycles", kind: .category, group: .cycle, label: "Unregelmäßige Zyklen", aggregation: .count),
        HealthDataType(id: "HKCategoryTypeIdentifierPersistentIntermenstrualBleeding", kind: .category, group: .cycle, label: "Anhaltende Zwischenblutungen", aggregation: .count),
        HealthDataType(id: "HKCategoryTypeIdentifierProlongedMenstrualPeriods", kind: .category, group: .cycle, label: "Verlängerte Periode", aggregation: .count),
        HealthDataType(id: "HKCategoryTypeIdentifierOvulationTestResult", kind: .category, group: .cycle, label: "Ovulationstest", aggregation: .count),
        HealthDataType(id: "HKCategoryTypeIdentifierCervicalMucusQuality", kind: .category, group: .cycle, label: "Zervixschleim", aggregation: .count),
        HealthDataType(id: "HKCategoryTypeIdentifierSexualActivity", kind: .category, group: .cycle, label: "Sexuelle Aktivität", aggregation: .count),
        HealthDataType(id: "HKCategoryTypeIdentifierPregnancy", kind: .category, group: .cycle, label: "Schwangerschaft", aggregation: .count),
        HealthDataType(id: "HKCategoryTypeIdentifierPregnancyTestResult", kind: .category, group: .cycle, label: "Schwangerschaftstest", aggregation: .count),
        HealthDataType(id: "HKCategoryTypeIdentifierProgesteroneTestResult", kind: .category, group: .cycle, label: "Progesterontest", aggregation: .count),
        HealthDataType(id: "HKCategoryTypeIdentifierLactation", kind: .category, group: .cycle, label: "Stillzeit", aggregation: .count),
        HealthDataType(id: "HKCategoryTypeIdentifierContraceptive", kind: .category, group: .cycle, label: "Verhütung", aggregation: .count),
        HealthDataType(id: "HKCategoryTypeIdentifierBleedingDuringPregnancy", kind: .category, group: .cycle, label: "Blutung in der Schwangerschaft", aggregation: .count),
        HealthDataType(id: "HKCategoryTypeIdentifierBleedingAfterPregnancy", kind: .category, group: .cycle, label: "Blutung nach der Schwangerschaft", aggregation: .count),
        HealthDataType(id: "HKCategoryTypeIdentifierAbdominalCramps", kind: .category, group: .symptoms, label: "Bauchkrämpfe", aggregation: .count),
        HealthDataType(id: "HKCategoryTypeIdentifierAcne", kind: .category, group: .symptoms, label: "Akne", aggregation: .count),
        HealthDataType(id: "HKCategoryTypeIdentifierAppetiteChanges", kind: .category, group: .symptoms, label: "Appetitveränderung", aggregation: .count),
        HealthDataType(id: "HKCategoryTypeIdentifierBladderIncontinence", kind: .category, group: .symptoms, label: "Blasenschwäche", aggregation: .count),
        HealthDataType(id: "HKCategoryTypeIdentifierBloating", kind: .category, group: .symptoms, label: "Blähungen", aggregation: .count),
        HealthDataType(id: "HKCategoryTypeIdentifierBreastPain", kind: .category, group: .symptoms, label: "Brustschmerzen", aggregation: .count),
        HealthDataType(id: "HKCategoryTypeIdentifierChestTightnessOrPain", kind: .category, group: .symptoms, label: "Engegefühl oder Schmerz in der Brust", aggregation: .count),
        HealthDataType(id: "HKCategoryTypeIdentifierChills", kind: .category, group: .symptoms, label: "Schüttelfrost", aggregation: .count),
        HealthDataType(id: "HKCategoryTypeIdentifierConstipation", kind: .category, group: .symptoms, label: "Verstopfung", aggregation: .count),
        HealthDataType(id: "HKCategoryTypeIdentifierCoughing", kind: .category, group: .symptoms, label: "Husten", aggregation: .count),
        HealthDataType(id: "HKCategoryTypeIdentifierDiarrhea", kind: .category, group: .symptoms, label: "Durchfall", aggregation: .count),
        HealthDataType(id: "HKCategoryTypeIdentifierDizziness", kind: .category, group: .symptoms, label: "Schwindel", aggregation: .count),
        HealthDataType(id: "HKCategoryTypeIdentifierDrySkin", kind: .category, group: .symptoms, label: "Trockene Haut", aggregation: .count),
        HealthDataType(id: "HKCategoryTypeIdentifierFainting", kind: .category, group: .symptoms, label: "Ohnmacht", aggregation: .count),
        HealthDataType(id: "HKCategoryTypeIdentifierFatigue", kind: .category, group: .symptoms, label: "Müdigkeit", aggregation: .count),
        HealthDataType(id: "HKCategoryTypeIdentifierFever", kind: .category, group: .symptoms, label: "Fieber", aggregation: .count),
        HealthDataType(id: "HKCategoryTypeIdentifierGeneralizedBodyAche", kind: .category, group: .symptoms, label: "Gliederschmerzen", aggregation: .count),
        HealthDataType(id: "HKCategoryTypeIdentifierHairLoss", kind: .category, group: .symptoms, label: "Haarausfall", aggregation: .count),
        HealthDataType(id: "HKCategoryTypeIdentifierHeadache", kind: .category, group: .symptoms, label: "Kopfschmerzen", aggregation: .count),
        HealthDataType(id: "HKCategoryTypeIdentifierHeartburn", kind: .category, group: .symptoms, label: "Sodbrennen", aggregation: .count),
        HealthDataType(id: "HKCategoryTypeIdentifierHotFlashes", kind: .category, group: .symptoms, label: "Hitzewallungen", aggregation: .count),
        HealthDataType(id: "HKCategoryTypeIdentifierLossOfSmell", kind: .category, group: .symptoms, label: "Geruchsverlust", aggregation: .count),
        HealthDataType(id: "HKCategoryTypeIdentifierLossOfTaste", kind: .category, group: .symptoms, label: "Geschmacksverlust", aggregation: .count),
        HealthDataType(id: "HKCategoryTypeIdentifierLowerBackPain", kind: .category, group: .symptoms, label: "Rückenschmerzen unten", aggregation: .count),
        HealthDataType(id: "HKCategoryTypeIdentifierMemoryLapse", kind: .category, group: .symptoms, label: "Vergesslichkeit", aggregation: .count),
        HealthDataType(id: "HKCategoryTypeIdentifierMoodChanges", kind: .category, group: .symptoms, label: "Stimmungsschwankungen", aggregation: .count),
        HealthDataType(id: "HKCategoryTypeIdentifierNausea", kind: .category, group: .symptoms, label: "Übelkeit", aggregation: .count),
        HealthDataType(id: "HKCategoryTypeIdentifierNightSweats", kind: .category, group: .symptoms, label: "Nachtschweiß", aggregation: .count),
        HealthDataType(id: "HKCategoryTypeIdentifierPelvicPain", kind: .category, group: .symptoms, label: "Beckenschmerzen", aggregation: .count),
        HealthDataType(id: "HKCategoryTypeIdentifierRapidPoundingOrFlutteringHeartbeat", kind: .category, group: .symptoms, label: "Herzrasen oder -klopfen", aggregation: .count),
        HealthDataType(id: "HKCategoryTypeIdentifierRunnyNose", kind: .category, group: .symptoms, label: "Laufende Nase", aggregation: .count),
        HealthDataType(id: "HKCategoryTypeIdentifierShortnessOfBreath", kind: .category, group: .symptoms, label: "Kurzatmigkeit", aggregation: .count),
        HealthDataType(id: "HKCategoryTypeIdentifierSinusCongestion", kind: .category, group: .symptoms, label: "Verstopfte Nebenhöhlen", aggregation: .count),
        HealthDataType(id: "HKCategoryTypeIdentifierSkippedHeartbeat", kind: .category, group: .symptoms, label: "Herzstolpern", aggregation: .count),
        HealthDataType(id: "HKCategoryTypeIdentifierSleepChanges", kind: .category, group: .symptoms, label: "Schlafveränderungen", aggregation: .count),
        HealthDataType(id: "HKCategoryTypeIdentifierSoreThroat", kind: .category, group: .symptoms, label: "Halsschmerzen", aggregation: .count),
        HealthDataType(id: "HKCategoryTypeIdentifierVaginalDryness", kind: .category, group: .symptoms, label: "Scheidentrockenheit", aggregation: .count),
        HealthDataType(id: "HKCategoryTypeIdentifierVomiting", kind: .category, group: .symptoms, label: "Erbrechen", aggregation: .count),
        HealthDataType(id: "HKCategoryTypeIdentifierWheezing", kind: .category, group: .symptoms, label: "Pfeifende Atmung", aggregation: .count),
        HealthDataType(id: "HKWorkoutTypeIdentifier", kind: .workout, group: .workouts, label: "Trainings", aggregation: .count),
        HealthDataType(id: "HKDataTypeIdentifierElectrocardiogram", kind: .ecg, group: .heart, label: "EKG", aggregation: .count),
        HealthDataType(id: "HKDataTypeIdentifierAudiogram", kind: .audiogram, group: .hearing, label: "Hörtest (Audiogramm)", aggregation: .count),
        HealthDataType(id: "HKDataTypeStateOfMind", kind: .stateOfMind, group: .mind, label: "Gemütszustand", aggregation: .count),
        HealthDataType(id: "HKClinicalTypeIdentifierAllergyRecord", kind: .clinical, group: .records, label: "Allergien", aggregation: .count),
        HealthDataType(id: "HKClinicalTypeIdentifierClinicalNoteRecord", kind: .clinical, group: .records, label: "Arztberichte", aggregation: .count),
        HealthDataType(id: "HKClinicalTypeIdentifierConditionRecord", kind: .clinical, group: .records, label: "Erkrankungen", aggregation: .count),
        HealthDataType(id: "HKClinicalTypeIdentifierImmunizationRecord", kind: .clinical, group: .records, label: "Impfungen", aggregation: .count),
        HealthDataType(id: "HKClinicalTypeIdentifierLabResultRecord", kind: .clinical, group: .records, label: "Laborergebnisse", aggregation: .count),
        HealthDataType(id: "HKClinicalTypeIdentifierMedicationRecord", kind: .clinical, group: .records, label: "Medikamente", aggregation: .count),
        HealthDataType(id: "HKClinicalTypeIdentifierProcedureRecord", kind: .clinical, group: .records, label: "Behandlungen", aggregation: .count),
        HealthDataType(id: "HKClinicalTypeIdentifierVitalSignRecord", kind: .clinical, group: .records, label: "Vitalzeichen (Akte)", aggregation: .count),
        HealthDataType(id: "HKClinicalTypeIdentifierCoverageRecord", kind: .clinical, group: .records, label: "Versicherung", aggregation: .count),
        HealthDataType(id: "HKCharacteristicTypeIdentifierDateOfBirth", kind: .characteristic, group: .profile, label: "Geburtsdatum", aggregation: .count),
        HealthDataType(id: "HKCharacteristicTypeIdentifierBiologicalSex", kind: .characteristic, group: .profile, label: "Biologisches Geschlecht", aggregation: .count),
        HealthDataType(id: "HKCharacteristicTypeIdentifierBloodType", kind: .characteristic, group: .profile, label: "Blutgruppe", aggregation: .count),
        HealthDataType(id: "HKCharacteristicTypeIdentifierFitzpatrickSkinType", kind: .characteristic, group: .profile, label: "Hauttyp", aggregation: .count),
        HealthDataType(id: "HKCharacteristicTypeIdentifierWheelchairUse", kind: .characteristic, group: .profile, label: "Rollstuhlnutzung", aggregation: .count),
        HealthDataType(id: "HKCharacteristicTypeIdentifierActivityMoveMode", kind: .characteristic, group: .profile, label: "Bewegungsziel-Art", aggregation: .count),
    ]
}
